#!/bin/bash


#convert windows line endings to unix line endings.
sed -i -e 's/\r$//' $1

#fix headers(format should be: #include <header here>).
sed -i -e 's/include "/include </g' $1
sed -i -e 's/"$/>/g' $1

#prepend std to standard types. Make sure that the standard type name is NOT a variable name and NOT a string.
sed -i -e "s/\([[:blank:]]\+\)map[[:blank:]]*</\1std::map</g" $1
sed -i -e "s/^map[[:blank:]]*</std::map</g" $1

sed -i -e 's/\([[:blank:]]\)string[[:blank:]]\+/\1std::string /g' $1
sed -i -e 's/^string[[:blank:]]\+/std::string /g' $1
sed -i -e "s/\([^'#include ']\)<string/\1<std::string/g" $1
sed -i -e 's/,string/, std::string/g' $1

sed -i -e "s/\([[:blank:]]\)list/\1std::list/g" $1

sed -i -e 's/\(<\|[[:blank:]]\)shared_ptr\([^[:alnum:]]\)/\1std::shared_ptr\2/g' $1

sed -i -e "s/\([[:blank:]]\)cout/\1std::cout/g" $1

sed -i -e "s/[[:blank:]]\+endl/ std::endl/g" $1
sed -i -e "s/<<endl/<< std::endl/g" $1

#insert a space between commas and characters.
sed -i -e 's/,\(\S\)/, \1/g' $1

#no spaces before open angle brackets and 1 space after close angle brackets.
sed -i -e "s/\([^'#include ']\)<\([^<].*\)>[[:blank:]]*/\1<\2> /g" $1

#covert > > to > >.
sed -i -e 's/\(<.*<.*\)>>/\1> >/g' $1

#remove tabs and spaces after open parentheses and before close parentheses.
sed -i -e 's/[[:blank:]]*([[:blank:]]*/(/g' $1
sed -i -e 's/[[:blank:]]*)[[:blank:]]*/)/g' $1

#remove new lines before close parentheses and close braces.
sed -i -e ':r;$!{N;br};s/\([[:blank:]]*\n\)\+[[:blank:]]*)/)/g' $1
sed -i -e ':r;$!{N;br};s/\([[:blank:]]*\n\)\+\([[:blank:]]*\)}/\n\2}/g' $1

#remove excess spaces/tabs
sed -i -e 's/[[:blank:]]\+$//g' $1

#space after ;
sed -i -e 's/;\(\S\)/; \1/g' $1

#convert postfix to prefix.
sed -i -e 's/\(?=[^;]\)\(?=[^ ]\)++/++\1/g' $1

#insert spaces before and after comparator operators. Operators should NOT be inside a string
#operator insert spaces before and after mathematical operators. Operators should NOT be inside a string.
sed -i -e "s/\(\".*\"\)*\([[:blank:]]*\)\(==\|!=\|>=\|<=\|=\)\([[:blank:]]*\)\(\".*\"\)*/\1 \3 \5/g" $1
sed -i -e 's/\((\S\+\)[[:blank:]]*%[[:blank:]]*\(\S.*)\)/\1 % \2/g' $1

#insert a space between for/if and open parenthesis.
sed -i -e "s/for(/for (/g" $1
sed -i -e "s/if(/if (/g" $1

#remove excess new lines
sed -i -e ':r;$!{N;br};s/\([^[:blank:]]\n\)\([[:blank:]]*\n\)\+/\1\n/g' $1
#sed -i -e ':r;$!{N;br};s/\([^[:blank:]]\n\)\([[:blank:]]*\n\)\+\(.*\Z\)/\1\3/g' $1